on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]

# cancel previous runs on the same PR
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: â›· PR tests

env:
  CI: true
  TARGET_SHA: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}

defaults:
  run:
    shell: bash

jobs:
  build-format-lint-test:
    name: ðŸš€ Build, format, lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.TARGET_SHA }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
      - name: 'ðŸ’„ Check format'
        run: pnpm format-check
      - name: 'ðŸ§ª Test linter'
        run: pnpm nx affected --targets=test-linter,test-type,test-circular
      - name: 'ðŸ§ª Run unit tests'
        run: pnpm nx run-many --target=test-unit
      - name: Install LCOV
        run: |
          sudo apt-get update
          sudo apt-get install lcov
      - name: 'ðŸ”ƒ Merge lcov files'
        run: ./scripts/merge-lcov.sh
      - name: ðŸ”Ž SonarCloud Scan
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-scan-action@v5.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
